In [3]:
# Import dependencies

import pandas as pd
from pathlib import Path

In [7]:
july_csv_path = Path("./202307.csv")
july_df = pd.read_csv(july_csv_path)
july_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual

In [8]:
july_df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [9]:
len(july_df)

106608

In [11]:
jan_csv_path = Path('./202401.csv')
jan_df = pd.read_csv(jan_csv_path)
jan_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member

In [13]:
jan_df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [14]:
len(jan_df)

50661

In [15]:
citibike_df = pd.concat([july_df, jan_df],ignore_index = True)

In [16]:
len(citibike_df)

157269

In [17]:
citibike_df.to_csv("./citibike_data.csv", index=False)

In [19]:
citibike_df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
157264,75E5CF948A4ADB77,electric_bike,2024-01-25 20:51:27,2024-01-25 20:59:16,Willow Ave & 12 St,HB505,Clinton St & 7 St,HB303,40.751920,-74.030396,40.74542,-74.03332,casual
157265,58DD5BF65F9B9E31,electric_bike,2024-01-27 09:03:41,2024-01-27 09:08:47,Southwest Park - Jackson St & Observer Hwy,HB401,Clinton St & 7 St,HB303,40.737551,-74.041664,40.74542,-74.03332,casual
157266,F0FBCE423BE48B08,classic_bike,2024-01-28 14:46:29,2024-01-28 14:51:43,Southwest Park - Jackson St & Observer Hwy,HB401,Clinton St & 7 St,HB303,40.737551,-74.041664,40.74542,-74.03332,member
157267,7DD51CAD2DBE7990,classic_bike,2024-01-10 08:03:47,2024-01-10 08:10:55,Southwest Park - Jackson St & Observer Hwy,HB401,Clinton St & 7 St,HB303,40.737551,-74.041664,40.74542,-74.03332,casual
157268,A48A85D58AFEBAA3,electric_bike,2024-01-29 12:22:47,2024-01-29 12:25:33,Willow Ave & 12 St,HB505,Bloomfield St & 15 St,HB203,40.751956,-74.030405,40.75453,-74.02658,member